package com.backend.service;

import com.backend.exception.ResourceNotFoundException;
import com.backend.model.Announcement;
import com.backend.repository.AnnouncementRepository;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;

@Service
@RequiredArgsConstructor
public class AnnouncementService {

    private final AnnouncementRepository announcementRepository;

    public Announcement createAnnouncement(String message, boolean autoGenerated) {
        Announcement announcement = new Announcement(
                null,
                message,
                LocalDateTime.now(),
                autoGenerated
        );
        return announcementRepository.save(announcement);
    }

    public List<Announcement> getAllAnnouncements() {
        return announcementRepository.findAll();
    }

    public Announcement getAnnouncementById(Long id) {
        return announcementRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Announcement not found with id " + id));
    }

    @Transactional
    public void deleteAnnouncement(Long id) {
        Announcement existing = announcementRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Announcement not found with id " + id));
        announcementRepository.delete(existing);
    }

    @Transactional
    public void createAutomaticAnnouncement(String message) {
        Announcement announcement = new Announcement();
        announcement.setMessage(message);
        announcement.setCreatedAt(LocalDateTime.now());
        announcementRepository.save(announcement);
    }

}
